TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: SLOWONLY_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  AUTO_RESUME: False
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/dl18206/Desktop/phd/code/personal/facebook/slowfast/dataset/annotations/standard/fg_only/few_shot/background
  PATH_PREFIX: /home/dl18206/Desktop/phd/data/panaf/panaf_sequence
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
TENSORBOARD:
  ENABLE: True
AUG:
  ENABLE: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-1
  LR_POLICY: cosine
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 1e-2
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slow
  MODEL_NAME: ResNet
  HEAD_ACT: none
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  LOSS_FUNC: unique_combination_loss
SAMPLING:
  BALANCED: False
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 1
  RETURN_FEATS: False
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 1
OUTPUT_DIR: model=slow_r50_unique_combination_loss