TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 192
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 20
  CHECKPOINT_TYPE: pytorch
  AUTO_RESUME: False
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/dl18206/Desktop/phd/code/personal/facebook/slowfast/dataset/annotations/standard/fg_only/overfit
  PATH_PREFIX: /home/dl18206/Desktop/phd/data/panaf/panaf_sequence
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
AUG:
  MANIFOLD_MIXUP: True
TAP:
  ENABLE: False
TENSORBOARD:
  ENABLE: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-1
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 1e-2
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slow
  MODEL_NAME: ManifoldMixupResNet
  HEAD_ACT: none
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  DETACH_FINAL_FC: False
  DETACH_HEAD: False
  REINIT_HEAD: False
SAMPLING:
  BALANCED: False
  BALANCE_TYPE: none
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 1
  RETURN_FEATS: True
  RETURN_CONV3D: True
  CHECKPOINT_FILE_PATH: /home/dl18206/Desktop/phd/code/personal/facebook/slowfast/checkpoint_epoch_00100.pyth
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 0
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 1
USE_SBATCH: False
OUTPUT_DIR: '.'
