TRAIN:
  ENABLE: True
  DATASET: nkinetics
  BATCH_SIZE: 10
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 100
  CHECKPOINT_FILE_PATH: projects/slow/SLOWONLY_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  MIXED_PRECISION: True
  AUTO_RESUME: False
TEST:
  ENABLE: True
  DATASET: nkinetics
  BATCH_SIZE: 10
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /home/kukushkin/imslowfast/dataset/annotations/fgbgmixup
  PATH_PREFIX: /home/kukushkin/imslowfast/dataset/videos/
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
  # DECODING_BACKEND: pyav #torchvision or pyav

FG_BG_MIXUP:
  ENABLE: True
  SUBTRACT_BG: 
    ENABLE: True
    ALPHA_MIN: 0.0
    ALPHA_MAX: 1.0
  ADD_BG2:
    ENABLE: False
    START_FROM_EPOCH: 0
  SELECT_RAND_BG_FRAME:
    ENABLE: False
    DUPLICATE_FRAME: False


TENSORBOARD:
  ENABLE: False
  CLASS_NAMES_PATH: /home/kukushkin/imslowfast/dataset/metadata/behaviours.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /home/kukushkin/imslowfast/dataset/metadata/behaviours.txt
  HISTOGRAM:
    ENABLE: True
    TOPK: 3
    SUBSET_PATH: /home/kukushkin/imslowfast/dataset/metadata/behaviours.txt
  WRONG_PRED_VIS: 
    ENABLE:   False
    #SUBSET_PATH: /home/kukushkin/imslowfast/dataset/gradcam
  MODEL_VIS:
    ENABLE: False
    MODEL_WEIGHTS: False
    ACTIVATIONS: False
    INPUT_VIDEO: False
    LAYER_LIST: ['s5/pathway0_res2']
    GRAD_CAM:
      ENABLE: False
      LAYER_LIST: ['s5/pathway0_res2']

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 2.5e-1
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 2.5e-2
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slow
  MODEL_NAME: ResNetFGBGMixup
  HEAD_ACT: none
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
USE_SBATCH: False
RNG_SEED: 0
LOG_PERIOD: 1
OUTPUT_DIR: 'results/model=slow_r50_ds=panaf_seq_with_negatives-epoch=bgfgmixup'
