TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 96
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_FILE_PATH: model=slow_r50_ds=panaf_seq/checkpoints/checkpoint_epoch_00090.pyth
  CHECKPOINT_TYPE: pytorch
  AUTO_RESUME: False
  CHECKPOINT_EPOCH_RESET: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 48
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /jmain02/home/J2AD001/wwp02/oxb63-wwp02/data/panaf_seq
  PATH_PREFIX: /jmain02/home/J2AD001/wwp02/oxb63-wwp02/data/panaf_20k/videos/original
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
AUG:
  MANIFOLD_MIXUP: True
TAP:
  ENABLE: False
TENSORBOARD:
  ENABLE: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-1
  LR_POLICY: cosine
  MAX_EPOCH: 90
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 1e-2
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slow
  MODEL_NAME: ManifoldMixupResNet
  HEAD_ACT: none
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
  DETACH_FINAL_FC: False
  DETACH_HEAD: True
  REINIT_HEAD: True
SAMPLING:
  BALANCED: False
  BALANCE_TYPE: none
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 96
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 1
USE_SBATCH: True
OUTPUT_DIR: model=slow-r50_pretrained=panaf-seq_method=manifold-mixup_ext=head-only
